name: CI and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Need previous commit to check version changes
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - name: Install dependencies
      if: success()
      run: bun install
    
    - name: Run typecheck
      id: typecheck
      if: success()
      run: bun run typecheck
    
    - name: Run build
      id: build
      if: success()
      run: bun run build
    
    - name: Run tests
      id: test
      if: success()
      run: bun test
    
    - name: Check version change
      id: version_check
      if: success()
      run: |
        # Get current version from package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        # Get previous version from the previous commit
        git show HEAD~1:package.json > previous-package.json 2>/dev/null || echo '{"version":"0.0.0"}' > previous-package.json
        PREVIOUS_VERSION=$(node -p "require('./previous-package.json').version")
        echo "Previous version: $PREVIOUS_VERSION"
        
        # Check if version changed
        if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
          echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
          echo "version_changed=true" >> $GITHUB_OUTPUT
        else
          echo "Version unchanged"
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Publish to npm
      if: success() && steps.version_check.outputs.version_changed == 'true' && github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish --access public